### PR TITLE
Update models.js

### PR DESCRIPTION
**Pull request by Joeao**
Fixed typo.

### CODE REVIEW

**Comment by kylefinley** [comment]
Hey @Joeao thanks for pull request!

I didn't realize that anyone was using this project. Just a heads up, I haven't update the project in quite some time so the code might be a little out of date.

Where you reading these [express auth tutorials](http://www.scotchmedia.com/tutorials)?
Is that how you found this project?

Kyle

**Comment by Joeao** [comment]
Hi @kylefinley ,

Yeah I google'd something along the lines of 'PassportJS tutorial' and noticed that your tutorials are using many of the technologies that I'm looking at using, so decided to start from step 1.

Really liking the tutorial so far, has made things very easy. I see it's unfinished, so hope that I can take it from there without getting too confused. I'm very new to both user authentication and NodeJS.

I'll soon be setting up MongoDB on an additional computer (I'd already done it before starting the tutorial), so should be able to write some basic instructions and/or references, for other users following the tutorial.

Joe

**Comment by kylefinley** [comment]
Joe,

It's great to hear the tutorials have been useful. 

> I see it's unfinished, so hope that I can take it from there without getting too confused.

Yes, I've transitioned a lot of my development work to [meteor](http://meteor.com/) so I haven't had the motivations to finish them.  If you have any questions please let me know. 

> I'll soon be setting up MongoDB on an additional computer (I'd already done it before starting the tutorial), so should be able to write some basic instructions and/or references, for other users following the tutorial.

That would be great. 

I've been trying to thinking of ways to make the tutorials more collaborative, if you have any ideas or suggestions please let me know.

**Comment by Joeao** [comment]
I've looked into Meteor and it looks really cool, it's definitely something I'll use in the future.

I'm not sure about collaborative tutorials as the style of instruction would keep changing, which may become confusing to the user. But to host tutorials on a wiki or something else that's editable by the user could work, so users can improve on what's already there.

I've noticed a few errors in the tutorial, just minor ones, although at least one issue breaks the tester, and the issue is from a few pages back so it took a while to find the problem. Is it worth me emailing amendments to you when I've completed the tutorial, or is it not something that you plan to continue supporting?

**Comment by kylefinley** [comment]
I would love to have any improvements that you are willing to submit. The markdown files for the tutorial are here:

https://github.com/scotchmedia/www.scotchmedia.com/blob/master/public/md/tutorials/express/authentication

For now, if you just want to send me a pull request, I'll update the site manually. I do like the idea of automating this process, though. I'll look into some wiki options for the future.

Thanks again,

Kyle

**Pull request merged**
